# Add configuration for server port
server:
  port: 8081

# Application name
spring:
  application:
    name: CUSTOMER-SERVICE

# Add configuration for eureka server
eureka:
  instance:
    prefer-ip-address: true
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url: http://localhost:8761/eureka/
