# Add configuration for server port
server:
  port: 8081

# Application name
spring:
  application:
    name: CUSTOMER-SERVICE

  # Add configuration for mysql database connection
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hotel_db?createDatabaseIfNoExist=true
    username: root
    password: amit123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Add configuration for eureka server
eureka:
  instance:
    prefer-ip-address: true
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url: http://localhost:8761/eureka/
